apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: expense
spec:
  storageClassName: "expense-ebs"
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 4Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:

      component: mysql 
      project: expense
      tier: db 
  serviceName: "nginx"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
      component: mysql 
      project: expense
      tier: db  # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: joindevops/mysql:v1.0
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
        volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: mysql