---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
    tier: web
    project: test-project
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #target-port